app/proposal/forms.py
# -*- coding: UTF-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Length, Required


msg_required = u"Это поле является обязательным."
msg_max = u"Количество символов не должно превышать {}."


class ProposalEditForm(FlaskForm):
    """Edit draft form."""
    name = TextAreaField(
        label=u'Название',
        validators=[
            Required(message=msg_required),
            Length(max=299, message=msg_max.format(299))
        ],
        id="draft_name"
    )
    cause = TextAreaField(
        label=u'Причина',
        validators=[
            Required(message=msg_required),
            Length(max=999, message=msg_max.format(999))
        ],
        id="draft_cause"
    )
    description = TextAreaField(
        label=u'Описание ситуации',
        validators=[
            Required(message=msg_required),
            Length(max=2999, message=msg_max.format(2999))
        ],
        id="description"
    )
    plan = TextAreaField(
        label=u'План действий',
        validators=[Length(max=2999, message=msg_max.format(2999))],
        id="plan"
    )
    submit = SubmitField('Сохранить изменения')


class ProposalDenyForm(FlaskForm):
    """Deny proposal form."""
    reason = TextAreaField(
        label=u'Причина отказа',
        validators=[
            Required(message=msg_required),
            Length(max=299, message=msg_max.format(299))
        ],
        id="reason"
    )
    submit = SubmitField('Отказать')

app/proposal/__init__.py
# -*- coding: UTF-8 -*-

from flask import Blueprint

proposal = Blueprint('proposal', __name__)

from . import views

app/proposal/views.py
# -*- coding: UTF-8 -*-

from datetime import datetime
from flask import render_template, redirect, url_for, abort, flash, current_app
from flask_login import login_required, current_user
from sqlalchemy import desc, and_
from sqlalchemy.exc import IntegrityError
from . import proposal
from .. import db
from ..models import Proposal, Gem, Trash
from .forms import ProposalEditForm, ProposalDenyForm

# ---------------------------------------------------------------------------- #
# ---------------------- Helper function ------------------------------------- #
# ---------------------------------------------------------------------------- #
def show_proposals_all(page):
    """Return all proposals."""
    _proposals = db.session.query(Proposal).filter(

    ).order_by(
        desc(Proposal.id)
    ).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    return _proposals

def show_proposals_my_open(page):
    """Return my proposals."""
    _proposals = db.session.query(Proposal).filter(
        Proposal.author==current_user.id
    ).order_by(
        desc(Proposal.id)
    ).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    return _proposals

def show_proposals_my_closed(page):
    """Return closed proposals."""
    _proposals = db.session.query(Trash).filter(
        Trash.author==current_user.id
    ).order_by(
        desc(Trash.id)
    ).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    return _proposals


# ---------------------------------------------------------------------------- #
# ------------------ Routes -------------------------------------------------- #
# ---------------------------------------------------------------------------- #
@proposal.route('/proposals/my/open/<int:page>', methods=['GET', 'POST'])
@login_required
def proposals_my_open(page=1):
    """Show my open proposals."""
    _proposals = show_proposals_my_open(page)
    return render_template('proposal/proposals_my.html', prpls=_proposals)


@proposal.route('/proposals/my/closed/<int:page>', methods=['GET', 'POST'])
@login_required
def proposals_my_closed(page=1):
    """Show my closed proposals."""
    _proposals = show_proposals_my_closed(page)
    return render_template('proposal/proposals_my_closed.html', prpls=_proposals)


@proposal.route('/proposals/all/<int:page>', methods=['GET', 'POST'])
@login_required
def proposals_all(page=1):
    """Show all proposals."""
    _proposals = show_proposals_all(page)
    return render_template('proposal/proposals_all.html', prpls=_proposals)


@proposal.route('/proposals/<int:id>')
@login_required
def a_proposal(id):
    """Show only one proposal with id."""
    _prpl = Proposal.query.get_or_404(id)
    return render_template('proposal/proposal.html', prpl=_prpl)


@proposal.route('/proposals/closed/<int:id>')
@login_required
def a_proposal_closed(id):
    """Show only one closed proposal with id."""
    _prpl = Trash.query.get_or_404(id)
    return render_template('proposal/proposal_closed.html', prpl=_prpl)


@proposal.route('/proposals/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def proposals_edit(id):
    """Edit proposal with id."""
    _proposal = Proposal.query.get_or_404(id)
    form = ProposalEditForm(obj=_proposal)
    if form.validate_on_submit():
        _proposal.name = form.name.data
        _proposal.cause = form.cause.data
        _proposal.description = form.description.data
        _proposal.plan = form.plan.data

        db.session.add(_proposal)
        try:
            db.session.commit()
            flash(u"Заявка на бриллиант изменена.", 'success')
        except IntegrityError as int_error:
            db.session.rollback()
            flash(u"Ошибка изменения заявки на бриллиант.", 'danger')
        return redirect(url_for('proposal.proposals_my_open', page=1))
    return render_template('proposal/proposals_edit.html', form=form)


@proposal.route('/proposals/<int:id>/accept', methods=['GET', 'POST'])
@login_required
def proposals_accept(id):
    """Accept proposal - make it a Gem."""
    if current_user.role == 0:
        abort(403)
    _proposal = Proposal.query.get_or_404(id)
    new_gem = Gem(
        created=datetime.utcnow(),
        author=_proposal.author,
        name =_proposal.name,
        cause=_proposal.cause,
        description=_proposal.description,
        plan=_proposal.plan,
        number=_proposal.number
    )
    db.session.add(new_gem)
    db.session.delete(_proposal)
    try:
        db.session.commit()
        flash(u"Заявка на бриллиант одобрена!", 'success')
    except IntegrityError:
        db.session.rollback()
        flash(u"Ошибка одобрения заявки на бриллиант.", 'danger')
    return redirect(url_for('proposal.proposals_all', page=1))


@proposal.route('/proposals/<int:id>/deny', methods=['GET', 'POST'])
@login_required
def proposals_deny(id):
    """Deny proposal."""
    _proposal = Proposal.query.get_or_404(id)
    form = ProposalDenyForm()
    if form.validate_on_submit():
        user_signature = "\n\n __(" + str(current_user.username) + ")__"
        _trash = Trash(
            created=datetime.utcnow(),
            author=_proposal.author,
            name =_proposal.name,
            cause=_proposal.cause,
            description=_proposal.description,
            plan=_proposal.plan,
            number=_proposal.number,
            trash_reason=form.reason.data+user_signature
        )
        db.session.add(_trash)
        db.session.delete(_proposal)
        try:
            db.session.commit()
            flash(u"В заявке на бриллиант отказано.", 'success')
        except IntegrityError:
            db.session.rollback()
            flash(u"Ошибка в отказе заявке на бриллиант.", 'danger')
        if current_user.role > 0:
            return redirect(url_for('proposal.proposals_all', page=1))
        return redirect(url_for('proposal.proposals_my_open', page=1))
    return render_template('proposal/proposals_deny.html', form=form, prpl=_proposal)


@proposal.route('/proposals/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def proposals_delete(id):
    """Delete proposal."""
    _proposal = Proposal.query.get_or_404(id)
    try:
        db.session.delete(_proposal)
        db.session.commit()
        flash(u"Заявка на бриллиант удалена.", 'success')
    except IntegrityError:
        db.session.rollback()
        flash(u"Ошибка удаления заявки на бриллиант.", 'danger')
    return redirect(url_for('proposal.proposals_my_open', page=1))


@proposal.route('/proposals/<int:id>/delete_from_trash', methods=['GET', 'POST'])
@login_required
def proposals_crean_trash(id):
    """Delete denied proposal from trash."""
    _trash = Trash.query.get_or_404(id)
    try:
        db.session.delete(_trash)
        db.session.commit()
        flash(u"Отказанная заявка на бриллиант удалена.", 'success')
    except IntegrityError:
        db.session.rollback()
        flash(u"Ошибка удаления отказанной заявки на бриллиант.", 'danger')
    return redirect(url_for('proposal.proposals_my_closed', page=1))

app/templates/proposal/proposal.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Заявка на бриллиант {{ prpl.number }}</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с заявкой">
                <a class="btn btn-default" href="{{ url_for('proposal.proposals_my_open', page=1) }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад к списку</a>
                <a class="btn btn-primary" href="{{ url_for('proposal.proposals_edit', id=prpl.id) }}">Редактировать <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a class="btn btn-warning" href="{{ url_for('proposal.proposals_deny', id=prpl.id) }}">Отказать <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></a>
                {% if current_user.role == 1 %}
                    <a class="btn btn-success" href="{{ url_for('proposal.proposals_accept', id=prpl.id) }}">Одобрить заявку <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a>
                {% endif %}
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 class="panel-title">Автор</h3></div>
                <div class="panel-body">{{ prpl.proposal_author.username }}</div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 class="panel-title">Дата создания</h3></div>
                <div class="panel-body">{{ moment(prpl.created).format('DD.MM.YY HH:mm') }}</div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body newspaper">
                    <h3>Название</h3>
                    {{ prpl.name|markdown }}
                    <h3>Причина</h3>
                    {{ prpl.cause|markdown }}
                    <h3>Описание</h3>
                    {{ prpl.description|markdown }}
                    <h3>План</h3>
                    {{ prpl.plan|markdown }}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

app/templates/proposal/proposal_closed.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Отмененная заявка на бриллиант {{ prpl.number }}</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с заявкой">
                <a class="btn btn-default" href="{{ url_for('proposal.proposals_my_closed', page=1) }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад к списку</a>
            </div>
            <hr>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 class="panel-title">Автор</h3></div>
                <div class="panel-body">{{ prpl.trash_author.username }}</div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 class="panel-title">Дата создания</h3></div>
                <div class="panel-body">
                    <p>{{ moment(prpl.created).format('DD.MM.YY HH:mm') }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body newspaper">
                    <h3>Название</h3>
                    {{ prpl.name|markdown }}
                    <h3>Причина</h3>
                    {{ prpl.cause|markdown }}
                    <h3>Описание</h3>
                    {{ prpl.description|markdown }}
                    <h3>План</h3>
                    {{ prpl.plan|markdown }}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-warning">
                <div class="panel-heading"><h3 class="panel-title">Причина отказа</h3></div>
                <div class="panel-body newspaper">{{ prpl.trash_reason|markdown }}</div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

app/templates/proposal/proposals_all.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Все заявки на бриллианты</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с заявкой">
                <a class="btn btn-default" href="{{ url_for('main.index') }}">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную
                </a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Создан</th>
                        <th>Автор</th>
                        <th>Название</th>
                        <th colspan="3">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if prpls %}
                        {% for prpl in prpls.items %}
                        <tr>
                            <td><a href="{{ url_for('proposal.a_proposal', id=prpl.id) }}">{{ prpl.number }}</a></td>
                            <td>{{ moment(prpl.created).format('DD.MM.YY') }}</td>
                            <td>{{ prpl.proposal_author.username }}</td>
                            <td>{{ prpl.name|markdown }}</td>
                            <td><a href="{{ url_for('proposal.proposals_edit', id=prpl.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                            <td><a href="{{ url_for('proposal.proposals_deny', id=prpl.id) }}"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true" title="Отказать в заявке"></a></td>
                            <td>
                                {% if current_user.role == 1 %}
                                    <a href="{{ url_for('proposal.proposals_accept', id=prpl.id) }}"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" title="Одобрить заявку"></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li {% if not prpls.has_prev %} class="disabled" {% endif %}>
                        <a href="{% if prpls.has_prev %} {{ url_for('proposal.proposals_all', page=prpls.page-1) }} {% else %}#{% endif %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>

                    {% for p in prpls.iter_pages() %}
                        {% if p %}
                            {% if p == prpls.page %}
                                <li class="active"><a href="{{ url_for('proposal.proposals_all', page=p) }}">{{ p }}</a></li>
                            {% else %}
                                <li><a href="{{ url_for('proposal.proposals_all', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% else %}
                            <li class="disabled"><a href="#">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    <li {% if not prpls.has_next %} class="disabled" {% endif %}>
                        <a href="{% if prpls.has_next %} {{ url_for('proposal.proposals_all', page=prpls.page+1) }} {% else %}#{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</div>
{% endblock %}

app/templates/proposal/proposals_deny.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Отказ в заявке на бриллиант</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с заявкой">
                <a class="btn btn-default" href="{{ url_for('proposal.proposals_all', page=1) }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад к списку</a>
                <a class="btn btn-primary" href="{{ url_for('proposal.a_proposal', id=prpl.id) }}">Назад к заявке</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form method="POST">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.reason.label }}
                    {{ form.reason(class="form-control") }}
                    {% if form.reason.errors %}
                        {% for error in form.reason.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
        </div>
    </div>

</div>
{% endblock %}

app/templates/proposal/proposals_edit.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Редактировать заявку</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group">
                <a class="btn btn-default" href="{{ url_for('proposal.proposals_all', page=1) }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> К списку заявок</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form method="POST">
            {{ form.csrf_token }}

                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(class="form-control") }}
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.cause.label }}
                    {{ form.cause(class="form-control", rows=6) }}
                    {% if form.cause.errors %}
                        {% for error in form.cause.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(class="form-control", rows=6) }}
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.plan.label }}
                    {{ form.plan(class="form-control", rows=6) }}
                    {% if form.plan.errors %}
                        {% for error in form.plan.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
        </div>
    </div>

</div> <!-- container -->
{% endblock %}

app/templates/proposal/proposals_my.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Мои открытые заявки на бриллианты</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с заявкой">
                <a class="btn btn-default" href="{{ url_for('main.index') }}">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную
                </a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Создан</th>
                        <th>Название</th>
                        <th colspan="4">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if prpls %}
                        {% for prpl in prpls.items %}
                        <tr>
                            <td><a href="{{ url_for('proposal.a_proposal', id=prpl.id) }}">{{ prpl.number }}</a></td>
                            <td>{{ moment(prpl.created).format('DD.MM.YY') }}</td>
                            <td>{{ prpl.name|markdown }}</td>
                            <td><a href="{{ url_for('proposal.proposals_edit', id=prpl.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                            <td><a href="{{ url_for('proposal.proposals_deny', id=prpl.id) }}"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true" title="Отказать в заявке"></a></td>
                            <td><a href="{{ url_for('proposal.proposals_delete', id=prpl.id) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true" title="Удалить"></a></td>
                            <td>
                                {% if current_user.role > 0 %}
                                    <a href="{{ url_for('proposal.proposals_accept', id=prpl.id) }}"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" title="Одобрить заявку"></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li {% if not prpls.has_prev %} class="disabled" {% endif %}>
                        <a href="{% if prpls.has_prev %} {{ url_for('proposal.proposals_my_open', page=prpls.page-1) }} {% else %}#{% endif %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>

                    {% for p in prpls.iter_pages() %}
                        {% if p %}
                            {% if p == prpls.page %}
                                <li class="active"><a href="{{ url_for('proposal.proposals_my_open', page=p) }}">{{ p }}</a></li>
                            {% else %}
                                <li><a href="{{ url_for('proposal.proposals_my_open', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% else %}
                            <li class="disabled"><a href="#">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    <li {% if not prpls.has_next %} class="disabled" {% endif %}>
                        <a href="{% if prpls.has_next %} {{ url_for('proposal.proposals_my_open', page=prpls.page+1) }} {% else %}#{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</div>
{% endblock %}

app/templates/proposal/proposals_my_closed.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Мои отмененные заявки на бриллианты</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с заявкой">
                <a class="btn btn-default" href="{{ url_for('main.index') }}">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную
                </a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Создан</th>
                        <th>Название</th>
                        <th>Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if prpls %}
                        {% for prpl in prpls.items %}
                        <tr>
                            <td><a href="{{ url_for('proposal.a_proposal_closed', id=prpl.id) }}">{{ prpl.number }}</a></td>
                            <td>{{ moment(prpl.created).format('DD.MM.YY') }}</td>
                            <td>{{ prpl.name|markdown }}</td>
                            <td><a href="{{ url_for('proposal.proposals_crean_trash', id=prpl.id) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true" title="Удалить"></a></td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li {% if not prpls.has_prev %} class="disabled" {% endif %}>
                        <a href="{% if prpls.has_prev %} {{ url_for('proposal.proposals_my_closed', page=prpls.page-1) }} {% else %}#{% endif %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>

                    {% for p in prpls.iter_pages() %}
                        {% if p %}
                            {% if p == prpls.page %}
                                <li class="active"><a href="{{ url_for('proposal.proposals_my_closed', page=p) }}">{{ p }}</a></li>
                            {% else %}
                                <li><a href="{{ url_for('proposal.proposals_my_closed', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% else %}
                            <li class="disabled"><a href="#">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    <li {% if not prpls.has_next %} class="disabled" {% endif %}>
                        <a href="{% if prpls.has_next %} {{ url_for('proposal.proposals_my_closed', page=prpls.page+1) }} {% else %}#{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</div>
{% endblock %}