app/gem/forms.py
# -*- coding: UTF-8 -*-

from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, SelectMultipleField
from wtforms.validators import Length, Required


msg_required = u"Это поле обязательно для заполнения."
msg_max = u"Количество символов не должно превышать {}."


class GemEditForm(FlaskForm):
    name = TextAreaField(
        label=u'Название',
        validators=[
            Required(message=msg_required),
            Length(max=299, message=msg_max.format(299))
        ],
        id='name'
    )

    cause = TextAreaField(
        label=u'Причина',
        validators=[
            Required(message=msg_required),
            Length(max=999, message=msg_max.format(999))
        ],
        id='cause'
    )

    description = TextAreaField(
        label=u'Описание',
        validators=[
            Required(message=msg_required),
            Length(max=2999, message=msg_max.format(2999))
        ],
        id='description'
    )

    plan = TextAreaField(
        label=u'План',
        validators=[
            Required(message=msg_required),
            Length(max=2999, message=msg_max.format(2999))
        ],
        id='plan'
    )

    submit = SubmitField(label=u'Сохранить')


class CommentAddForm(FlaskForm):
    comment = TextAreaField(
        label=u'Комментарий',
        validators=[
            Required(message=msg_required),
            Length(max=499, message=msg_max.format(499))
        ],
        id='comment'
    )
    submit = SubmitField(label=u'Добавить комментарий')


class EditTeamForm(FlaskForm):
    member = SelectMultipleField(label=u'Выбирите члена группы')
    submit = SubmitField(label=u'Сохранить')

app/gem/__init__.py
# -*- coding: UTF-8 -*-

from flask import Blueprint

gem = Blueprint('gem', __name__)

from . import views

app/gem/views.py
# -*- coding: UTF-8 -*-

from datetime import datetime
from flask import render_template, redirect, abort, url_for, flash, current_app, request
from flask_login import login_required, current_user
from sqlalchemy import or_, and_, desc
from sqlalchemy.exc import IntegrityError
from . import gem
from .. import db
from ..models import User, Department, Gem, Comment, Team
from .forms import GemEditForm, CommentAddForm, EditTeamForm



# ---------------------------------------------------------------------------- #
# ------------------------------ Gems ---------------------------------------- #
# ---------------------------------------------------------------------------- #

@gem.route('/gems/all', methods=['GET', 'POST'])
@gem.route('/gems/all/<int:page>', methods=['GET', 'POST'])
@login_required
def gems(page=1):
    """Show all the gems."""    
    gems = db.session.query(Gem).filter().order_by(
        desc(Gem.created)
    ).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    return render_template('gem/gems.html', gems=gems)


@gem.route('/gems/my')
@gem.route('/gems/my/<int:page>', methods=['GET', 'POST'])
@login_required
def gems_my(page=1):
    """Show gems of current user."""
    gems = db.session.query(Gem).filter(
        Gem.author==current_user.id
    ).order_by(desc(Gem.created)).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    return render_template('gem/gems_my.html', gems=gems)


@gem.route('/gems/<int:id>', methods=['GET', 'POST'])
@login_required
def a_gem(id):
    """Show the Gem with id and all the corresponding data."""
    _gem = Gem.query.get_or_404(id)
    _comments = db.session.query(Comment).filter(Comment.gem_id==_gem.id).order_by(desc(Comment.created))
    _team = db.session.query(Team).filter(Team.gem_id==id).order_by(Team.user_id)
    _team_ids = [x.user_id for x in _team]
    form = CommentAddForm()
    if form.validate_on_submit():
        new_comment = Comment(
            created=datetime.utcnow(),
            comment=form.comment.data,
            author=current_user.id,
            gem_id=_gem.id
        )
        db.session.add(new_comment)
        try:
            db.session.commit()
            flash(u"Новый комментарий добавлен!", 'success')
        except IntegrityError:
            db.session.rollback()
            flash(u"Ошибка добавления комментария.", 'danger')
        return redirect(url_for('gem.a_gem', id=_gem.id))
    return render_template('gem/gem.html', gem=_gem, comments=_comments, form=form, team=_team, team_ids=_team_ids)


@gem.route('/gems/<int:gem_id>/edit', methods=['GET', 'POST'])
@login_required
def gems_edit(gem_id):
    """Edit the gem with id."""
    gem = Gem.query.get_or_404(gem_id)
    form = GemEditForm(obj=gem)
    if form.validate_on_submit():
        gem.name = form.name.data
        gem.cause = form.cause.data
        gem.description = form.description.data
        gem.plan = form.plan.data
        db.session.add(gem)
        try:
            db.session.commit()
            flash(u"Информация о бриллианте успешно изменена!", 'success')
        except IntegrityError:
            db.session.rollback() 
            flash(u"Ошибка изменения информации о бриллианте.", 'danger')
        return redirect(url_for('gem.gems'))
    return render_template('gem/gem_edit.html', form=form, _gem=gem)


@gem.route('/gems/<int:id>/close', methods=['GET', 'POST'])
@login_required
def gems_close(id):
    """Close the Gem with id as completed successfully."""
    if current_user.role == 0:
        abort(403)
    gem = Gem.query.get_or_404(id)
    gem.closed_at = datetime.utcnow()
    db.session.add(gem)
    try:
        db.session.commit()
        flash(u"Биллиант успешно завершен!", 'success')
    except IntegrityError:
        db.session.rollback()
        flash(u"Ошибка завершения бриллианта.", 'danger')
    return redirect(url_for('gem.gems'))


@gem.route('/gems/<int:gemid>/team', methods=['GET', 'POST'])
@login_required
def edit_team(gemid):
    """Add a new team member to the Gem with id."""
    _gem = Gem.query.get_or_404(gemid)

    _users = db.session.query(User).filter(User.active==1).order_by(User.username)
    users_lst = [(str(user.id), str(user.username)) for user in _users]

    form = EditTeamForm()
    form.member.choices = users_lst
    if form.validate_on_submit():
        for k in form.member.data:
            team_member = Team(
                gem_id=gemid,
                user_id=int(k)
            )
            db.session.add(team_member)
        try:
            db.session.commit()
            flash(u"Новые члены команды добавлены.", 'success')
        except IntegrityError:
            db.session.rollback()
            flash(u"Ошибка добавления членов команды.", 'danger')
        return redirect(url_for('gem.a_gem', id=gemid))
    return render_template('gem/team_edit.html', form=form)


@gem.route('/gems/<int:gemid>/team/<int:member_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_team_member(gemid, member_id):
    """Deletion the User member_id from Gem team."""
    _team = db.session.query(Team).filter(Team.gem_id==gemid, Team.user_id==member_id).first()
    if _team:
        try:
            db.session.delete(_team)
            db.session.commit()
            flash(u"Член команды исключен.", 'success')
        except IntegrityError:
            db.session.rollback()
            flash(u"Ошибка исключения члена команды.", 'danger')
    return redirect(url_for('gem.a_gem', id=gemid))


@gem.route('/gems/participation', methods=['GET', 'POST'])
@login_required
def gems_participation():
    """Show gems where user participates."""
    _participation = db.session.query(Team.gem_id).filter(Team.user_id==current_user.id).group_by(Team.gem_id).all()
    gems = []
    if _participation:
        gem_ids = [x.gem_id for x in _participation]
        gems = db.session.query(Gem).filter(
            Gem.id.in_(gem_ids)
        ).order_by(
            desc(Gem.created)
        ).all()
    return render_template('gem/gems_participation.html', gems=gems)

app/templates/gem/gem.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Бриллиант {{ gem.number }}</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Gem actions">
                <!--Назад к списку бриллиантов-->
                <a class="btn btn-default" href="{{ url_for('gem.gems') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад к списку</a>
                <!--Автор бриллианта - простой пользователь-->
                {% if current_user.id == gem.author and current_user.role == 0 %}
                    <!--Редактировать-->
                    <a class="btn btn-primary" href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}">Редактировать <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <!--Добавить членов команды-->
                    <a class="btn btn-primary" href="{{ url_for('gem.edit_team', gemid=gem.id) }}">Добавить команду <span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                {% endif %} 
                <!--Автор бриллианта - член совета или админ -->
                {% if current_user.id == gem.author and current_user.role in [1, 2] %}
                    <!--Редактировать-->
                    <a class="btn btn-primary" href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}">Редактировать <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <!--Добавить членов команды-->
                    <a class="btn btn-primary" href="{{ url_for('gem.edit_team', gemid=gem.id) }}">Добавить команду <span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                    <!--Закрыть бриллиант-->
                    <a class="btn btn-success" href="{{ url_for('gem.gems_close', id=gem.id) }}">Закрыть <span class="glyphicon glyphicon-ok" aria-hidden="true"></a>
                {% endif %}
                <!--Член совета или админ, но не автор бриллианта-->
                {% if current_user.id != gem.author and current_user.role in [1, 2] %}
                    <!--Редактировать-->
                    <a class="btn btn-primary" href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}">Редактировать <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                    <!--Закрыть бриллиант-->
                    <a class="btn btn-success" href="{{ url_for('gem.gems_close', id=gem.id) }}">Закрыть <span class="glyphicon glyphicon-ok" aria-hidden="true"></a>
                {% endif %}
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 class="panel-title">Информация о бриллианте</h3></div>
                <div class="panel-body">
                    <dl>
                        <dt>Автор</dt>
                        <dd>{{ gem.gem_author.username }}</dd>
                    </dl>
                    <dl>
                        <dt>Дата одобрения заявки на бриллиант</dt>
                        <dd>{{ moment(gem.created).format('DD.MM.YYYY HH:mm') }}</dd>
                    </dl>
                    <dl>
                        <dt>Дата закрытия бриллианта</dt>
                        <dd>
                            {% if gem.closed_at is not none %}
                            {{ moment(gem.closed_at).format('DD.MM.YYYY HH:mm') }}
                            {% endif %}
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 class="panel-title">Команда бриллианта</h3></div>
                <div class="panel-body">
                    {% if team%}
                    <ol>
                        {% if current_user.id == gem.author %}
                            {% for member in team %}
                                <li>{{ member.team_member.username }} <a href="{{ url_for('gem.delete_team_member', gemid=gem.id, member_id=member.user_id)}}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></li>
                            {% endfor %}
                        {% else %}
                            {% for member in team %}
                                <li>{{ member.team_member.username }}</li>
                            {% endfor %}
                        {% endif %}
                    </ol>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body newspaper">
                    <h3>Название</h3>
                    {{ gem.name|markdown }}
                    <hr>

                    <h3>Причина</h3>
                    {{ gem.cause|markdown }}
                    <hr>

                    <h3>Описание</h3>
                    {{ gem.description|markdown }}
                    <hr>

                    <h3>План</h3>
                    {{ gem.plan|markdown }}
                </div>
            </div>
        </div>
    </div>

    <hr>
    
    <div class="row">
        <div class="col-md-12">
            <h2>Комментарии к бриллианту</h2>
        </div>
    </div>

    {% if current_user['role'] > 0 or current_user.id == gem.author or current_user.id in team_ids %}
    <div class="row">
        <div class="col-md-12">
            <form class="form" method="POST">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.comment.label }}
                    {{ form.comment(class="form-control") }}
                    {% if form.comment.errors %}
                        {% for error in form.comment.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
            <hr>
        </div>
    </div>
    {% endif %}
    
    {% for comment in comments %}
    <div class="row">
        <div class="col-md-12">
            <blockquote >
                {{ comment.comment|markdown }}
                <footer>{{ comment.comment_author.username }} <cite title="Source Title">{{ moment(comment.created).format('LLL') }}</cite></footer>
            </blockquote>
        </div>
    </div>
    {% endfor %}

</div> <!--container-->

{% endblock %}

app/templates/gem/gem_edit.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Редактировать бриллианта {{ _gem.number }}</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group">
                <a class="btn btn-default" href="{{ url_for('gem.gems') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> К списку бриллиантов</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form method="POST">
            {{ form.csrf_token }}

                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(class="form-control") }}
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.cause.label }}
                    {{ form.cause(class="form-control", rows=6) }}
                    {% if form.cause.errors %}
                        {% for error in form.cause.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(class="form-control", rows=6) }}
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.plan.label }}
                    {{ form.plan(class="form-control", rows=6) }}
                    {% if form.plan.errors %}
                        {% for error in form.plan.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
        </div>
    </div>

</div> <!-- container -->
{% endblock %}

app/templates/gem/gems.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Все бриллианты</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group">
                <a class="btn btn-default" href="{{ url_for('main.index') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Создан</th>
                        <th>Закрыт</th>
                        <th>Автор</th>
                        <th>Название</th>
                        <th colspan="2">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if gems %}
                        {% for gem in gems.items %}
                        <tr {{ "class=success" if gem.closed_at is not none }}>
                            <td><a href="{{ url_for('gem.a_gem', id=gem.id) }}">{{ gem.number }}</a></td>
                            <td>{{ moment(gem.created).format('DD.MM.YY') }}</td>
                            {% if gem.closed_at is none %}
                                <td></td>
                            {% else %}
                                <td><p>{{ moment(gem.closed_at).format('DD.MM.YYYY') }}</p></td>
                            {% endif %}
                            <td>{{ gem.gem_author.username }}</td>
                            <td>{{ gem.name|markdown }}</td>
                            
                            {% if current_user.role in [1, 2]%}
                                <td><a href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                                {% if gem.closed_at is not none %}
                                    <td></td>
                                {% else %}
                                    <td><a href="{{ url_for('gem.gems_close', id=gem.id) }}"><span class="glyphicon glyphicon-ok" aria-hidden="true" title="Завершить успешно"></a></td>
                                {% endif %}
                            {% elif current_user.role == 0 and current_user.id == gem.author %}
                                <td><a href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                                <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li {% if not gems.has_prev %} class="disabled" {% endif %}>
                        <a href="{% if gems.has_prev %} {{ url_for('gem.gems', page=gems.page-1) }} {% else %}#{% endif %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>

                    {% for p in gems.iter_pages() %}
                        {% if p %}
                            {% if p == gems.page %}
                                <li class="active"><a href="{{ url_for('gem.gems', page=p) }}">{{ p }}</a></li>
                            {% else %}
                                <li><a href="{{ url_for('gem.gems', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% else %}
                            <li class="disabled"><a href="#">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    <li {% if not gems.has_next %} class="disabled" {% endif %}>
                        <a href="{% if gems.has_next %} {{ url_for('gem.gems', page=gems.page+1) }} {% else %}#{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</div>

{% endblock %}

app/templates/gem/gems_my.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Мои бриллианты</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group">
                <a class="btn btn-default" href="{{ url_for('main.index') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Создан</th>
                        <th>Закрыт</th>
                        <th>Автор</th>
                        <th>Название</th>
                        <th colspan="2">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if gems %}
                        {% for gem in gems.items %}
                        <tr {{ "class=success" if gem.closed_at is not none }}>
                            <td><a href="{{ url_for('gem.a_gem', id=gem.id) }}">{{ gem.number }}</a></td>
                            <td>{{ moment(gem.created).format('DD.MM.YY') }}</td>
                            {% if gem.closed_at is none %}
                                <td></td>
                            {% else %}
                                <td><p>{{ moment(gem.closed_at).format('DD.MM.YYYY') }}</p></td>
                            {% endif %}
                            <td>{{ gem.gem_author.username }}</td>
                            <td>{{ gem.name|markdown }}</td>
                            
                            {% if current_user.role in [1, 2]%}
                                <td><a href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                                {% if gem.closed_at is not none %}
                                    <td></td>
                                {% else %}
                                    <td><a href="{{ url_for('gem.gems_close', id=gem.id) }}"><span class="glyphicon glyphicon-ok" aria-hidden="true" title="Завершить успешно"></a></td>
                                {% endif %}
                            {% elif current_user.role == 0 and current_user.id == gem.author %}
                                <td><a href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                                <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li {% if not gems.has_prev %} class="disabled" {% endif %}>
                        <a href="{% if gems.has_prev %} {{ url_for('gem.gems', page=gems.page-1) }} {% else %}#{% endif %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                    {% for p in gems.iter_pages() %}
                        {% if p %}
                            {% if p == gems.page %}
                                <li class="active"><a href="{{ url_for('gem.gems_my', page=p) }}">{{ p }}</a></li>
                            {% else %}
                                <li><a href="{{ url_for('gem.gems_my', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% else %}
                            <li class="disabled"><a href="#">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    <li {% if not gems.has_next %} class="disabled" {% endif %}>
                        <a href="{% if gems.has_next %} {{ url_for('gem.gems', page=gems.page+1) }} {% else %}#{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</div>

{% endblock %}

app/templates/gem/gems_participation.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Бриллианты</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group">
                <a class="btn btn-default" href="{{ url_for('main.index') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Создан</th>
                        <th>Закрыт</th>
                        <th>Автор</th>
                        <th>Название</th>
                        <th colspan="2">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if gems %}
                        {% for gem in gems %}
                        <tr {{ "class=success" if gem.closed_at is not none }}>
                            <td><a href="{{ url_for('gem.a_gem', id=gem.id) }}">{{ gem.number }}</a></td>
                            <td>{{ moment(gem.created).format('DD.MM.YY') }}</td>
                            {% if gem.closed_at is none %}
                                <td></td>
                            {% else %}
                                <td><p>{{ moment(gem.closed_at).format('DD.MM.YYYY') }}</p></td>
                            {% endif %}
                            <td>{{ gem.gem_author.username }}</td>
                            <td>{{ gem.name|markdown }}</td>
                            
                            {% if current_user.role in [1, 2]%}
                                <td><a href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                                {% if gem.closed_at is not none %}
                                    <td></td>
                                {% else %}
                                    <td><a href="{{ url_for('gem.gems_close', id=gem.id) }}"><span class="glyphicon glyphicon-ok" aria-hidden="true" title="Завершить успешно"></a></td>
                                {% endif %}
                            {% elif current_user.role == 0 and current_user.id == gem.author %}
                                <td><a href="{{ url_for('gem.gems_edit', gem_id=gem.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редактировать"></a></td>
                                <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock %}

app/templates/gem/team_edit.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
    
    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Команда бриллианта</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <form class="form" method="POST">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.member.label }}
                    {{ form.member(class="form-control", type="checkbox", id="members") }}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
        </div>
    </div>

</div>
{% endblock %}