app/draft/forms.py
# -*- coding: UTF-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Length, Required


msg_required = u"Это поле является обязательным."
msg_max = u"Количество символов не должно превышать {}."


class DraftRegistrationForm(FlaskForm):
    """New draft registration form."""
    name = TextAreaField(
        label=u'Название',
        validators=[
            Required(message=msg_required),
            Length(max=299, message=msg_max.format(299))
        ],
        id="draft_name"
    )
    cause = TextAreaField(
        label=u'Причина',
        validators=[
            Required(message=msg_required),
            Length(max=999, message=msg_max.format(999))
        ],
        id="draft_cause"
    )
    description = TextAreaField(
        label=u'Описание ситуации',
        validators=[
            Required(message=msg_required),
            Length(max=2999, message=msg_max.format(2999))
        ],
        id="description"
    )
    plan = TextAreaField(
        label=u'План действий',
        validators=[Length(max=2999, message=msg_max.format(2999))],
        id="plan"
    )
    submit = SubmitField(label=u'Создать')


class DraftEditForm(FlaskForm):
    """Edit draft form."""
    name = TextAreaField(
        label=u'Название',
        validators=[
            Required(message=msg_required),
            Length(max=299, message=msg_max.format(299))
        ],
        id="draft_name"
    )
    cause = TextAreaField(
        label=u'Причина',
        validators=[
            Required(message=msg_required),
            Length(max=999, message=msg_max.format(999))
        ],
        id="draft_cause"
    )
    description = TextAreaField(
        label=u'Описание ситуации',
        validators=[
            Required(message=msg_required),
            Length(max=2999, message=msg_max.format(2999))
        ],
        id="description"
    )
    plan = TextAreaField(
        label=u'План действий',
        validators=[Length(max=2999, message=msg_max.format(2999))],
        id="plan"
    )
    submit = SubmitField('Сохранить изменения')

app/draft/__init__.py
# -*- coding: UTF-8 -*-

from flask import Blueprint

draft = Blueprint('draft', __name__)

from . import views

app/draft/views.py
# -*- coding: UTF-8 -*-

from datetime import datetime
from flask import render_template, redirect, url_for, flash, current_app
from flask_login import login_required, current_user
from sqlalchemy import or_, and_, desc
from sqlalchemy.exc import IntegrityError
from . import draft
from .. import db
from ..models import Draft, Proposal
from .forms import DraftRegistrationForm, DraftEditForm


# ---------------------------------------------------------------------------- #
# ---------------------- Helper functions ------------------------------------ #
# ---------------------------------------------------------------------------- #

def show_drafts(page):
    """Return drafts for current user."""
    _drft = db.session.query(Draft).filter(
        Draft.author==current_user.id
    ).order_by(
        desc(Draft.id)
    ).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
    )
    return _drft

# ---------------------------------------------------------------------------- #
# ------------------------- Drafts ------------------------------------------- #
# ---------------------------------------------------------------------------- #

@draft.route('/drafts/all', methods=['GET', 'POST'])
@draft.route('/drafts/all/<int:page>', methods=['GET', 'POST'])
@login_required
def drafts(page=1):
    """Show all drafts for current user."""
    _drafts = show_drafts(page)
    return render_template('draft/drafts.html', drafts=_drafts)


@draft.route('/drafts/<int:id>', methods=['GET', 'POST'])
@login_required
def a_draft(id):
    """Show a draft with id."""
    _draft = Draft.query.get_or_404(id)
    return render_template('draft/draft.html', draft=_draft)


@draft.route("/drafts/add", methods=['GET', 'POST'])
@login_required
def drafts_add():
    """Create a new draft."""
    form = DraftRegistrationForm()
    if form.validate_on_submit():
        _draft = Draft(
            created=datetime.utcnow(),
            author=current_user.id,
            name=form.name.data,
            cause=form.cause.data,
            description=form.description.data,
            plan=form.plan.data,
            number=Draft._generate_number()
        )
        db.session.add(_draft)
        try:
            db.session.commit()
            flash(u"Новый черновик создан!", 'success')
        except IntegrityError:
            db.session.rollback()
            flash(u"Ошибка: черновик не создан!", 'danger')
        return redirect(url_for('draft.drafts'))
    return render_template('draft/drafts_add.html', form=form)


@draft.route("/drafts/<int:id>/delete")
@login_required
def drafts_delete(id):
    """Delete draft."""
    _draft = Draft.query.get_or_404(id)
    db.session.delete(_draft)
    try:
        db.session.commit()
        flash(u"Черновик удален!", 'success')
    except IntegrityError:
        db.session.rollback()
        flash(u"Ошибка: черновик не удален!", 'danger')
    return redirect(url_for('draft.drafts'))
    

@draft.route("/drafts/<int:id>/edit", methods=['GET', 'POST'])
@login_required
def drafts_edit(id):
    """Edit a draft with id."""
    _draft = Draft.query.get_or_404(id)
    form = DraftEditForm(obj=_draft)
    if form.validate_on_submit():
        _draft.name = form.name.data
        _draft.cause = form.cause.data
        _draft.description = form.description.data
        _draft.plan = form.plan.data
        db.session.add(_draft)
        try:
            db.session.commit()
            flash(u"Черновик изменен!", 'success')
        except IntegrityError:
            db.session.rollback()
            flash(u"Ошибка: черновик не изменен!", 'danger')
        return redirect(url_for('draft.drafts'))
    return render_template('draft/drafts_edit.html', form=form)


@draft.route("/drafts/<int:id>/make_proposal")
@login_required
def drafts_make_proposal(id):
    """Make a proposal from draft."""
    _draft = Draft.query.get_or_404(id)
    new_proposal = Proposal(
        author=_draft.author,
        name=_draft.name,
        cause=_draft.cause,
        description=_draft.description,
        plan=_draft.plan,
        number=_draft.number
    )
    db.session.add(new_proposal)  # create new proposal
    db.session.delete(_draft)  # delete a draft
    try:
        db.session.commit()
        flash(u"Вы успешно подали заявку на бриллиант. Ожидайте одобрения заявки.", 'success')
    except IntegrityError:
        db.session.rollback()
        flash(u"Ошибка подачи заявки на бриллиант!", 'danger')
    return redirect(url_for('draft.drafts'))

app/templates/draft/draft.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Черновик {{ draft.number }}</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с черновиком">
                <a class="btn btn-default" href="{{ url_for('draft.drafts') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад к списку</a>
                <a class="btn btn-primary" href="{{ url_for('draft.drafts_edit', id=draft.id) }}">Редактировать <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a class="btn btn-danger" href="{{ url_for('draft.drafts_delete', id=draft.id) }}">Удалить <span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                <a class="btn btn-success" href="{{ url_for('draft.drafts_make_proposal', id=draft.id) }}">Подать заявку <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span></a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body newspaper">
                    <h3>Название</h3>
                    {{ draft.name|markdown }}
                    <h3>Причина</h3>
                    {{ draft.cause|markdown }}
                    <h3>Описание</h3>
                    {{ draft.description|markdown }}
                    <h3>План</h3>
                    {{ draft.plan|markdown }}
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

app/templates/draft/drafts.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Черновики</h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с черновиком">
                <a class="btn btn-default" href="{{ url_for('main.index') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> На главную</a>
                <a class="btn btn-primary" href="{{ url_for('draft.drafts_add') }}">Создать новый черновик</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Название</th>
                        <th colspan="3">Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% if drafts %}
                        {% for draft in drafts.items %}
                        <tr>
                            <td><a href="{{ url_for('draft.a_draft', id=draft.id) }}">{{ draft.number }}</a></td>
                            <td>{{ draft.name|markdown }}</td>
                            <td><a href="{{ url_for('draft.drafts_delete', id=draft.id) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true" title="Удалить"></a></td>
                            <td><a href="{{ url_for('draft.drafts_edit', id=draft.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="Редиктировать"></a></td>
                            <td><a href="{{ url_for('draft.drafts_make_proposal', id=draft.id) }}"><span class="glyphicon glyphicon-share-alt" aria-hidden="true" title="Подать заявку"></a></td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li {% if not drafts.has_prev %} class="disabled" {% endif %}>
                        <a href="{% if drafts.has_prev %} {{ url_for('draft.drafts', page=drafts.page-1) }} {% else %}#{% endif %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                    </li>

                    {% for p in drafts.iter_pages() %}
                        {% if p %}
                            {% if p == drafts.page %}
                                <li class="active"><a href="{{ url_for('draft.drafts', page=p) }}">{{ p }}</a></li>
                            {% else %}
                                <li><a href="{{ url_for('draft.drafts', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% else %}
                            <li class="disabled"><a href="#">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    <li {% if not drafts.has_next %} class="disabled" {% endif %}>
                        <a href="{% if drafts.has_next %} {{ url_for('draft.drafts', page=drafts.page+1) }} {% else %}#{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</div>
{% endblock %}

app/templates/draft/drafts_add.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Новый черновик</h1></div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с черновиком">
                <a class="btn btn-default" href="{{ url_for('draft.drafts') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> К списку черновиков</a>
            </div>
            <hr>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <form method="POST">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(class="form-control") }}
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.cause.label }}
                    {{ form.cause(class="form-control", rows=6) }}
                    {% if form.cause.errors %}
                        {% for error in form.cause.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(class="form-control", rows=6) }}
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.plan.label }}
                    {{ form.plan(class="form-control", rows=6) }}
                    {% if form.plan.errors %}
                        {% for error in form.plan.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
        </div>
    </div>

</div> <!-- container -->
{% endblock %}

app/templates/draft/drafts_edit.html
{% extends "_base.html" %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h1>Редактировать черновик </h1></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="btn-group" role="group" aria-label="Действия с черновиком">
                <a class="btn btn-default" href="{{ url_for('draft.drafts') }}"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> К списку черновиков</a>
            </div>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form method="POST">
            {{ form.csrf_token }}

                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(class="form-control") }}
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.cause.label }}
                    {{ form.cause(class="form-control", rows=6) }}
                    {% if form.cause.errors %}
                        {% for error in form.cause.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.description.label }}
                    {{ form.description(class="form-control", rows=6) }}
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.plan.label }}
                    {{ form.plan(class="form-control", rows=6) }}
                    {% if form.plan.errors %}
                        {% for error in form.plan.errors %}
                            <p class="text-danger"><small>{{ error }}</small></p>
                        {% endfor %}
                    {% endif %}
                </div>
                {{  form.submit(class="btn btn-success") }}
            </form>
        </div>
    </div>

</div> <!-- container -->
{% endblock %}